version: '2'

networks:
    simple_web_server_network:
        ipam:
            driver: default
            config:
                - subnet: 172.20.0.0/16

services:
    flask1:
        restart: always
        build: ./flask
        command: run.sh
        networks:
            simple_web_server_network:
                ipv4_address: 172.20.0.2

    flask2:
        restart: always
        build: ./flask
        command: run.sh
        networks:
            simple_web_server_network:
                ipv4_address: 172.20.0.3

    flask3:
        restart: always
        build: ./flask
        command: run.sh
        networks:
            simple_web_server_network:
                ipv4_address: 172.20.0.4
